#!/bin/bash
USBASP='-P usb -c usbasp'

HEXFILE=gamepad2usb.hex

#CLOCK='-B 12MHz'
#CLOCK='-B 1.0'
CLOCK='-B 10.0'

# Run script with root privileges
if [ "$USER" != "root" ]
then sudo $0;
fi

#if password not entered then exit
if [ "$USER" != "root" ]
then exit 0
fi

echo $HEXFILE

avrdude -p m8 $USBASP -Uflash:w:$HEXFILE $CLOCK

# Fuse high byte:
# 0xc9 = 1 1 0 0   1 0 0 1 <-- BOOTRST (boot reset vector at 0x0000)
#        ^ ^ ^ ^   ^ ^ ^------ BOOTSZ0
#        | | | |   | +-------- BOOTSZ1
#        | | | |   + --------- EESAVE (don't preserve EEPROM over chip erase)
#        | | | +-------------- CKOPT (full output swing)
#        | | +---------------- SPIEN (allow serial programming)
#        | +------------------ WDTON (WDT not always on)
#        +-------------------- RSTDISBL (reset pin is enabled)
# Fuse low byte:
# 0x9f = 1 0 0 1   1 1 1 1
#        ^ ^ \ /   \--+--/
#        | |  |       +------- CKSEL 3..0 (external >8M crystal)
#        | |  +--------------- SUT 1..0 (crystal osc, BOD enabled)
#        | +------------------ BODEN (BrownOut Detector enabled)
#        +-------------------- BODLEVEL (2.7V)
avrdude -p m8 $USBASP -Uhfuse:w:0xc9:m -Ulfuse:w:0x9f:m $CLOCK

echo $HEXFILE was used
